#Reference: https://www.mkdocs.org/user-guide/configuration/

site_name: 'OpenDI: JSON Schema (DRAFT)'
repo_url: https://github.com/IAmKelDev/draft-opendi-json-schema
edit_uri: blob/dev/docs     #URI Partial, added to repo URL to link to editable version of user's current page

docs_dir: "docs"            #Local directory for docs .md files

nav:
  - Schema: 'index.md'
  - 'Sample Data': 'test-data.md'
  - 'OpenDI Home': "https://iamkeldev.github.io/draft-opendi-home"
  - 'OpenDI Glossary': 'https://iamkeldev.github.io/draft-opendi-home/OpenDI Glossary'

# Exclude _Role Page Template.md
exclude_docs: |
  _*.md

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  navigation_depth: 5

# extra_javascript:
#   - schema_doc.min.js


# Material is a third-party theme
# https://squidfunk.github.io/mkdocs-material/
# theme:
#   name: material

#   features:
#     - navigation.tabs
#     - navigation.tabs.sticky
#     - toc.integrate
#     - toc.follow
  
#   extra_css:
#     - schema_doc.css
  
#   palette: 
#     - scheme: default