#Reference: https://www.mkdocs.org/user-guide/configuration/

site_name: 'OpenDI: JSON Schema (DRAFT)'
repo_url: https://github.com/IAmKelDev/draft-opendi-json-schema
edit_uri: blob/dev/docs     #URI Partial, added to repo URL to link to editable version of user's current page

docs_dir: "docs"            #Local directory for docs .md files

nav:
  - Schema: 'index.md'
  - 'Sample Data': 'test-data.md'
  - 'OpenDI Home': "https://iamkeldev.github.io/draft-opendi-home"
  - 'OpenDI Glossary': 'https://iamkeldev.github.io/draft-opendi-home/OpenDI Glossary'

# Exclude _Role Page Template.md
exclude_docs: |
  _*.md

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  navigation_depth: 5


# # Material is a third-party theme
# # https://squidfunk.github.io/mkdocs-material/
# theme:
#   name: material

#   features:
#     - toc.follow
  
#   palette: 
#     # Palette toggle for light mode
#     - scheme: default
#       toggle:
#         icon: material/brightness-7 
#         name: Switch to dark mode

#     # Palette toggle for dark mode
#     - scheme: slate
#       toggle:
#         icon: material/brightness-4
#         name: Switch to light mode